INSERT INTO Task VALUES (1, 'COVID-19', 'Excused Leave', true);
INSERT INTO Task VALUES (2, 'Chrismas Eve - 4 hours', 'Excused Leave', true);
INSERT INTO Task VALUES (3, 'New Years Eve 31 Dec - 4 hours', 'Excused Leave', true);
INSERT INTO Task VALUES (4, 'Staff Birthday - 4 hours', 'Excused Leave', true);
INSERT INTO Task VALUES (5, 'Inwerken', 'Inwerken', true);
INSERT INTO Task VALUES (6, 'IT issue', 'IT Management', true); 
INSERT INTO Task VALUES (7, 'Uren', 'Personal Admin', true);
INSERT INTO Task VALUES (8, 'Expenses', 'Personal Admin', true);
INSERT INTO Task VALUES (9, 'AO', 'Sick', true);
INSERT INTO Task VALUES (10, 'Doctor', 'Sick', true);
INSERT INTO Task VALUES (11, 'Coaching', 'Human Resource', true);
INSERT INTO Task VALUES (12, 'Development Review', 'Human Resource', true);
INSERT INTO Task VALUES (13, 'Events Committe', 'Human Resource', true);
INSERT INTO Task VALUES (14, 'Goalsetting', 'Human Resource', true);
INSERT INTO Task VALUES (15, 'HR Comite', 'Human Resource', true);
INSERT INTO Task VALUES (16, 'KPI', 'Human Resource', true);
INSERT INTO Task VALUES (17, 'MBO', 'Human Resource', true);
INSERT INTO Task VALUES (18, 'Overleg met HR', 'Human Resource', true);
INSERT INTO Task VALUES (19, 'Begeleiding', 'Inwerken', true);
INSERT INTO Task VALUES (20, 'Kennis overdracht', 'Inwerken', true);
INSERT INTO Task VALUES (21, 'Traineeship', 'Inwerken', true);
INSERT INTO Task VALUES (22, 'Uniform training', 'Inwerken', true);
INSERT INTO Task VALUES (23, 'Atlassian system maintenance', 'IT Management', true);
INSERT INTO Task VALUES (24, 'CRM system maintenance', 'IT Management', true);
INSERT INTO Task VALUES (25, 'Cloudforge - SVN', 'IT Management', true);
INSERT INTO Task VALUES (26, 'General IT', 'IT Management', true);
INSERT INTO Task VALUES (27, 'Team City', 'IT Management', true);
INSERT INTO Task VALUES (28, 'Operations B&M', 'Marketing & Branding BearingPoint', true);
INSERT INTO Task VALUES (29, 'Content Recruitment', 'Marketing & Branding BearingPoint', true);
INSERT INTO Task VALUES (30, 'MTS Development', 'Be Informed Modeller', true);