INSERT INTO Task VALUES (0, 'COVID-19', 'Excused Leave', true);
INSERT INTO Task VALUES (0, 'Chrismas Eve - 4 hours', 'Excused Leave', true);
INSERT INTO Task VALUES (0, 'New Years Eve 31 Dec - 4 hours', 'Excused Leave', true);
INSERT INTO Task VALUES (0, 'Staff Birthday - 4 hours', 'Excused Leave', true);
INSERT INTO Task VALUES (0, 'Inwerken', 'Inwerken', true);
INSERT INTO Task VALUES (0, 'IT issue', 'IT Management', true); 
INSERT INTO Task VALUES (0, 'Uren', 'Personal Admin', true);
INSERT INTO Task VALUES (0, 'Expenses', 'Personal Admin', true);
INSERT INTO Task VALUES (0, 'AO', 'Sick', true);
INSERT INTO Task VALUES (0, 'Doctor', 'Sick', true);
INSERT INTO Task VALUES (0, 'Coaching', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'Development Review', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'Events Committe', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'Goalsetting', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'HR Comite', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'KPI', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'MBO', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'Overleg met HR', 'Human Resource', true);
INSERT INTO Task VALUES (0, 'Begeleiding', 'Inwerken', true);
INSERT INTO Task VALUES (0, 'Kennis overdracht', 'Inwerken', true);
INSERT INTO Task VALUES (0, 'Traineeship', 'Inwerken', true);
INSERT INTO Task VALUES (0, 'Uniform training', 'Inwerken', true);
INSERT INTO Task VALUES (0, 'Atlassian system maintenance', 'IT Management', true);
INSERT INTO Task VALUES (0, 'CRM system maintenance', 'IT Management', true);
INSERT INTO Task VALUES (0, 'Cloudforge - SVN', 'IT Management', true);
INSERT INTO Task VALUES (0, 'General IT', 'IT Management', true);
INSERT INTO Task VALUES (0, 'Team City', 'IT Management', true);